name: FRONT CI CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: git code checkout
        uses: actions/checkout@v3

      # - name: Make env file
      #   run: |
      #     echo "${{ secrets.ENV_PROPERTIES }}" > ".env"
      #     cat .env

      - name: docker setup
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo-front:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/demo-front:cache
          cache-to: type=inline

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 2022
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/demo-front:latest
          docker stop demo-front || true
          docker rm demo-front || true
          docker run -d --name demo-front -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/demo-front:latest
